### ISSUE TITLE
KeyInvalid

### ISSUE THREAD

**Issue by ryfloyd** [infusionsoft/Official-API-Python-Library#11]
I think I'm following the correct process to obtain an API Key and have it associated to my InfusionSoft Account.

1. I created a Mashery Account, and retrieved the API_KEY and SECRET_KEY https://keys.developer.infusionsoft.com/apps/mykeys
2. Using this python library, and the examples provided, I put in the following code replacing {appName} with the name of my InfusionSoft subdomain:
```
infusionsoft = Infusionsoft('{appName}', settings.INFUSION_API_KEY)
contact = {'FirstName' : 'John', 'LastName' : 'Doe', 'Email' : 'johndoe@email.com'}
print infusionsoft.ContactService('add', contact)
```
3. And it errors out with KeyInvalid.

What am I doing wrong? Do I first need to obtain an OAUTH key?

**Comment by kressaty** [comment]
You'll have to obtain an oauth token, correct. The keys from Mashery allow you to go through the OAuth process.
