### ISSUE TITLE
Commit breaks entire functionality of library

### ISSUE THREAD

**Issue by alechewitt** [infusionsoft/Official-API-Python-Library#19]
Removing `return function` in this commit (https://github.com/infusionsoft/Official-API-Python-Library/commit/a9b88d745c64bab2d9191a39a82ed265e6800e69) has broken the entire library: 

Last time I install a library without specifying a commit hash!

**Comment by gera-cameron** [comment]
Yes this is broken and needs fixed. I rolled back to a previous version as it broke my production sync service. Please address! Thank you!
