### ISSUE TITLE
Could you add some query range examples?

### ISSUE THREAD

**Issue by ericchaves** [infusionsoft/Official-API-Python-Library#9]
Hi guys,

I'm studying Infusion's python API and I could not figure out how to perform queries whose field values are not exact. For example, given the following code:

```
infusionsoft = Infusionsoft(credentials['app'], credentials['key'])

limit = 1000
page = 0

query = {'Id': '14' }
returnFields = ['Id','Name','TabId']

print infusionsoft.DataService('query', 'DataFormGroup', limit, page, query, returnFields)
```

How could I query all items whose Id are greater than -1? Or how can I query all items in the DataFormGroup table without any restriction?

Thanks in advance for any help,

Eric

**Comment by jeremiahmarks** [comment]
Basically you could use what you have now, except make this change:

    query = {}  

I am not 100% sure that that will work in the helper libraries, but I do know for sure that it does work, [here is an example of what it is that I use](https://github.com/jeremiahmarks/infusImport/blob/58ed1a8f1862b93845fb81beebbc09a797a9b347/ISServer.py#L197-215) in one of the integrations that I wrote.    If you want to see it in action, you can clone that repo and run the getall.py file.  That will pull every record that you can directly access through the API down into a CSV file locally.

**Comment by ericchaves** [comment]
@jeremiahmarks thanks for help! Your project gave me a good staring direction.
